[package]
name = "slotted-egraphs"
version = "0.0.17"
edition = "2021"
description = "E-Graphs with name binding"
license = "Apache-2.0 OR MIT"
repository = "https://github.com/memoryleak47/slotted-egraphs/"

[features]
explanations = []
checks = []
tracing = ["tracing/max_level_trace", "tracing/release_max_level_trace"]
# ??? no_tracing = ["tracing/max_level_debug", "tracing/release_max_level_off"]

[package.metadata.docs.rs]
features = ["explanations"]

[dependencies]
fnv = "1.0.7"
tracing  = { version = "0.1", features = ["attributes"] }

[dev-dependencies]
symbol_table = { version = "0.3", features = ["global"]}
rand = "0.8.5"

[profile.release]
debug = true